<div class="span6 offset3">
	<div class="header-farmacias">
		<h1><img src="/img/layout/logo-farmacia.png" alt="Farmacia" /> farmacias en concepción</h1>
		<select>
			<option value="">Mas cercano primero</option>
		</select>

		<div class="btn-group">
			<button class="btn disabled">Ver como: </button>
			<button class="btn active"><i class="icon-th-list"></i> Listado</button>
			<button class="btn"><i class="icon-map-marker"></i> Mapa</button>
		</div>
	</div>
	<div class="clearfix"></div>
</div>

<div class="span8 offset2">
	<div class="media">
		<a class="pull-left" href="#">
			<img class="media-object img-polaroid" src="http://placehold.it/64x64">
			<span class="turno"></span>
		</a>
		<div class="media-body">
			<h4 class="media-heading"><a href="#">Farmacia</a></h4>
			<span class="muted">
				Dirección<br />
				Horario
			</span>
		</div>
	</div>
	<div class="media">
		<a class="pull-left" href="#">
			<img class="media-object img-polaroid" src="http://placehold.it/64x64">
		</a>
		<div class="media-body">
			<div class="span3">
				<h4 class="media-heading"><a href="#">Farmacia</a></h4>
				<span class="muted">
					Dirección<br />
					Horario
				</span>
			</div>
			<div class="span3 padding-top">
				<i class="icon-star"></i>
				<i class="icon-star"></i>
				<i class="icon-star"></i>
				<i class="icon-star"></i>
				<i class="icon-star-empty"></i>
			</div>
			<div class="span3 padding-top">
				<i class="icon-flag"></i> 2 denuncias
			</div>
			<div class="span3 padding-top">
				<i class="icon-comment"></i> 5 comentarios
			</div>
		</div>
	</div>
	<div class="media">
		<a class="pull-left" href="#">
			<img class="media-object img-polaroid" src="http://placehold.it/64x64">
		</a>
		<div class="media-body">
			<h4 class="media-heading"><a href="#">Farmacia</a></h4>
			<span class="muted">
				Dirección<br />
				Horario
			</span>
		</div>
	</div>
	<div class="media">
	</div>

	<div class="pagination pagination-centered">
      	<ul>
			<li class="disabled"><a href="#">«</a></li>
			<li class="active"><a href="#">1</a></li>
			<li><a href="#">2</a></li>
			<li><a href="#">3</a></li>
			<li><a href="#">4</a></li>
			<li><a href="#">5</a></li>
			<li><a href="#">»</a></li>
     	</ul>
    </div>
</div>
