<div class="bg-header">
	<div class="span6 offset3">

		<div class="logo">
			<img src="/img/layout/quieromifarmacia.jpg" alt="Quiero mi Farmacia" />
		</div>

		<div class="ubicacion">
			<label>Tu ubicación:</label>
			<input type="text" id="ubicacion" class="input-xlarge" value="Concepción, Chile" readonly />
		</div>

	</div>
</div>

<div class="row-fluid buscador-portada">
	<div class="span3 offset3 box-left">
		<img src="/img/portada/logo-farmacias.png" alt="Farmacias" />
		<div class="linea-right"></div>

	    <div class="control-group">
	        <div class="controls row-fluid">
	          	<div class="span12 row">
	          		<select class="span12">
						<option value="" disabled selected>Mas cercano primero</option>
					</select>
	          	</div>
	        </div>
	        <div class="controls row-fluid">
	          	<div class="span12 row">
	          		<select class="span12">
						<option value="" disabled selected>Todas las farmacias</option>
					</select>
	          	</div>
	        </div>
	        <div class="controls row-fluid">
	          	<div class="span12 row">
					<button class="span8 offset2 btn btn-large btn-farmacia">Buscar</button>
	          	</div>
	        </div>
	    </div>
	</div>
	<div class="span3 box-right">
		<img src="/img/portada/logo-medicamentos.png" alt="Medicamentos" />
		<div class="linea-right"></div>

		<div class="control-group">
	        <div class="controls row-fluid">
	          	<div class="span12 row">
	          		<input type="text" class="span12" placeholder="Nombre del medicamento" />
	          	</div>
	        </div>
	        <div class="controls row-fluid">
	          	<div class="span12 row">
	          		<select class="span12">
						<option value="">Mayor a menor precio</option>
						<option value="">Menor a mayor precio</option>
					</select>
	          	</div>
	        </div>
	        <div class="controls row-fluid">
	          	<div class="span12 row">
					<button class="span8 offset2 btn btn-large btn-medicamento">Buscar</button>
	          	</div>
	        </div>
	    </div>
	</div>
</div>