<?php echo $this->doctype();echo "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php echo $this->headTitle();echo "\n";?>
<?php echo $this->headMeta();echo "\n"; ?>
<?php echo $this->headLink();echo "\n";?>
<?php echo $this->headScript();echo "\n";?>
</head>
<body>

<div class="navbar navbar-inverse navbar-static-top">
	<div class="navbar-inner">
	<?php /*
		<div class="container">
			<ul class="nav">
				<li <?php if($this->active == 1) echo 'class="active"'; ?>><a href="#">Quiero mi farmacia</a></li>
				<li <?php if($this->active == 2) echo 'class="active"'; ?>><a href="/farmacias/">Farmacias</a></li>
				<li <?php if($this->active == 3) echo 'class="active"'; ?>><a href="#">Medicamentos</a></li>
			</ul>

			<form class="navbar-search pull-left">
				<input type="text" class="search-query" placeholder="¿Qué estas buscando?">
			</form>
		</div>
	*/ ?>
	<button type="button" class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
	<a class="visible-phone visible-tablet brand" href="/">Quier mi Farmacia</a>
    <div class="nav-collapse collapse" style="height: 0px;">
      	<ul class="nav">
			<li <?php if($this->active == 1) echo 'class="active"'; ?>><a href="#">Quiero mi farmacia</a></li>
			<li <?php if($this->active == 2) echo 'class="active"'; ?>><a href="/farmacias/">Farmacias</a></li>
			<li <?php if($this->active == 3) echo 'class="active"'; ?>><a href="#">Medicamentos</a></li>
		</ul>
    </div>

	</div>
	<div class="clearfix"></div>
</div>

<div class="container-fluid">
	<div class="row-fluid">

	    <?php echo $this->layout()->content ?>

	</div>
</div>

<footer>

	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span6 offset3">
				<span class="muted">© 2012 quieromifarmacia</span>
				<a href="#">¿Que es esto?</a>
				<a href="#">Preguntas frecuentes</a>
				<a href="#">Contáctanos</a>
			</div>
		</div>
	</div>

</footer>

</body>
</html>

